# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QR코드 만들기' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QR코드 만들기
  pod 'QRCodeReader.swift', '~> 10.1.0'
end
